#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

busybox mkdir -p /dev/block
busybox mknod -m 0644 /dev/block/bml8 b 137 8
mbusybox knod -m 0644 /dev/block/bml9 b 137 9
busybox mknod -m 0644 /dev/block/bml10 b 137 10
busybox mknod -m 0644 /dev/block/stl8 b 138 8
busybox mknod -m 0644 /dev/block/stl9 b 138 9
busybox mknod -m 0644 /dev/block/stl10 b 138 10

busybox mknod -m 0644 /dev/block/mmcblk0 b 179 0
busybox mknod -m 0644 /dev/block/mmcblk0p1 b 179 1
busybox mknod -m 0644 /dev/block/mmcblk0p3 b 179 3

busybox mkdir /cache
busybox mkdir /proc
busybox mkdir /sys

busybox insmod /lib/modules/fsr.ko
busybox insmod /lib/modules/fsr_stl.ko

busybox date >>/boot.txt
exec >>/boot.txt 2>&1
busybox cd /
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox rm /init

busybox dd bs=512 if=/dev/block/bml8 of=/stage1/boot.bin

eval $(grep -m 1 -A 1 BOOT_IMAGE_OFFSETS /stage1/boot.bin | tail -n 1)

load_offset=$boot_offset
load_len=$boot_len

busybox mount -t ext4 /dev/block/mmcblk0p3 /cache

if test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	busybox rm -fr /cache/.startrecovery
	load_offset=$recovery_offset
	load_len=$recovery_len

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox rm -rf /cache

busybox dd bs=512 if=/stage1/boot.bin skip=$load_offset count=$load_len | zcat | cpio -i

if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	busybox cp lpm.rc init.rc
	busybox rm init.smdkc110.rc
fi

busybox umount /sys
busybox umount /proc
busybox date >> /boot.txt

busybox rm -rf /stage1 
busybox rm -rf /dev/*

export PATH="${_PATH}"

exec /init
